### ISSUE TITLE
Why didn't you use thread_group instead of vector<boost::thread>?

### ISSUE THREAD

**Issue by iamazeem** [alexott/boost-asio-examples#5]
Hello Alex,

You've done a great job by writing these examples! Helped me a lot to learn `Boost::Asio` concepts.
I have a question. Could you please clarify the use of `vector<boost::thread>` instead of `thread_group`?
Using `thread_group` would be a bit easy and straightforward. Is it your own decision or there is something to it?

Thanks!

**Comment by alexott** [comment]
Hi Azeem

When I wrote these examples (almost 10 years ago), there were some problems
with thread_group (or it wasn't added to boost yet? - don't remember).
That's why I selected another thread library

On Sunday, 19 June 2016, Azeem Sajid notifications@github.com wrote:

> Hello Alex,
> 
> You've done a great job by writing these examples! Helped me a lot to
> learn Boost::Asio concepts.
> I have a question. Could you please clarify the use of vectorboost::thread
> instead of thread_group?
> Using thread_group would be a bit easy and straightforward. Is it your own
> decision or there is something to it?
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/alexott/boost-asio-examples/issues/5, or mute the
> thread
> https://github.com/notifications/unsubscribe/AAB2hvyfgx81fJLlYntk0WnBwom_XJ43ks5qNVSmgaJpZM4I5Lba
> .

## 

With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Comment by iamazeem** [comment]
Oh, alright. Thanks!
